"""chatcli - Give any chat LLM local CLI superpowers.

Usage:
    chatcli              # Interactive REPL
    chatcli "query"      # Single-shot query
    chatcli --print "query"  # Single-shot query for scripts
    chatcli --setup      # Create local project config
    chatcli --setup --global  # Create user config shared by all projects
    chatcli --global "query"  # Use the user config even inside a project
"""

import sys
import getpass
import json
import os
from pathlib import Path

import yaml

from .config import Config
from .ui import REPL


# ── Minimal config generated by `chatcli --setup`. ─────────────────────
# This file contains only the most common settings.
# For a complete reference with all available options, see config.example.yaml:
#   https://github.com/cjh-1001/chatcli/blob/master/config.example.yaml
#
# Built-in tools not listed below are also available — they are added
# automatically at startup. You only need to list tools here if you want
# to override their default permission group.
# ───────────────────────────────────────────────────────────────────────

_MINIMAL_CONFIG_TEMPLATE = """\
# chatcli configuration
# See config.example.yaml for all available options.

provider:
  provider: anthropic        # anthropic | openai | openai-compatible | text-tools
  model: claude-sonnet-4-6
  # api_key: sk-...          # Prefer CHATCLI_API_KEY env var instead
  # api_base: https://...    # For custom endpoints (Ollama, vLLM, etc.)
  max_tokens: 8192
  thinking: true
  thinking_budget: 4096

# Tool permissions. Tools not listed here use their built-in defaults.
permissions:
  auto:                      # Run without asking
    - read_file
    - glob
    - grep
    - list_dir
    - web_search
    - web_fetch
  ask:                       # Ask for confirmation
    - bash
    - write_file
    - edit_file
  deny: []                   # Never allow
  protect_sensitive_files: true

max_tool_rounds: 80
min_tool_rounds: 5              # evidence-heavy tasks only; normal chat can answer directly
auto_compress: true
context_file: .chatcli/context.md
"""


def _detected_provider_settings() -> dict[str, str]:
    """Detect provider/model from environment variables."""
    try:
        provider = os.environ.get("CHATCLI_PROVIDER", "").strip()
        model = os.environ.get("CHATCLI_MODEL", "").strip()
        api_base = os.environ.get("CHATCLI_API_BASE", "").strip()

        if not provider:
            if os.environ.get("ANTHROPIC_API_KEY"):
                provider = "anthropic"
            elif os.environ.get("MIMO_API_KEY"):
                provider = "openai-compatible"
                api_base = api_base or "https://api.xiaomimimo.com/v1"
            elif os.environ.get("OPENAI_API_KEY"):
                provider = "openai"
            else:
                provider = "anthropic"
    except Exception:
        provider = "anthropic"
        model = ""
        api_base = ""

    if not model:
        model = "claude-sonnet-4-6" if provider == "anthropic" else "gpt-4.1"

    return {"provider": provider, "model": model, "api_base": api_base}


def _render_config(settings: dict[str, str] | None = None) -> str:
    """Render a config file from the minimal template, injecting provider settings."""
    s = settings or {}
    provider = s.get("provider", "anthropic")
    model = s.get("model", "claude-sonnet-4-6")
    api_key = s.get("api_key", "")
    api_base = s.get("api_base", "")

    lines: list[str] = []
    for line in _MINIMAL_CONFIG_TEMPLATE.splitlines():
        if line.startswith("  provider:") and not line.startswith("  provider: "):
            pass  # skip the comment header line
        elif line.startswith("  provider:"):
            lines.append(f"  provider: {json.dumps(provider)}        # anthropic | openai | openai-compatible | text-tools")
        elif line.startswith("  model:"):
            lines.append(f"  model: {json.dumps(model)}")
            if api_key:
                lines.append("  api_key: " + json.dumps(api_key))
        elif line.startswith("  # api_key:"):
            if not api_key:
                lines.append(line)
        elif line.startswith("  # api_base:") and api_base:
            lines.append("  api_base: " + json.dumps(api_base))
        elif line.startswith("  # api_base:"):
            lines.append(line)
        else:
            lines.append(line)

    return "\n".join(lines) + "\n"


def setup_config(
    config_file: Path | None = None,
    settings: dict[str, str] | None = None,
    quiet: bool = False,
) -> Path:
    """Create default config file."""
    config_file = config_file or Config.default_config_file()
    config_dir = config_file.parent

    if config_file.exists():
        if not quiet:
            print(f"Config already exists at {config_file}")
        return config_file

    config_dir.mkdir(parents=True, exist_ok=True)
    config_file.write_text(_render_config(settings), encoding="utf-8")

    # Also create a sample context file
    context_file = config_dir / "context.md"
    if not context_file.exists():
        context_file.write_text(
            "# Project Context\n\n"
            "Add project-specific instructions here. "
            "The model will read this file to understand your project.\n\n"
            "## Tech Stack\n- ...\n\n"
            "## Conventions\n- ...\n",
            encoding="utf-8",
        )

    if quiet:
        return config_file

    print(f"Created config at {config_file}")
    print(f"Created context at {context_file}")
    print("\nNext: set your API key via environment variable:")
    print("  export ANTHROPIC_API_KEY=sk-ant-...")
    print("  export OPENAI_API_KEY=sk-...")
    print("  export MIMO_API_KEY=...")
    print("  export CHATCLI_API_KEY=...")
    print("\nSee config.example.yaml for all available options:")
    print("  https://github.com/cjh-1001/chatcli/blob/master/config.example.yaml")
    return config_file


def _prompt_default(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def _choose_provider(default: str) -> tuple[str, str, str]:
    choices = [
        ("anthropic", "Anthropic", "claude-sonnet-4-6", ""),
        ("openai", "OpenAI", "gpt-4.1", ""),
        ("openai-compatible", "OpenAI-compatible", "gpt-4.1", ""),
        ("text-tools", "Text-tools", "gpt-4.1", ""),
        ("openai-compatible", "MiMo / xiaomimimo.com", "claude-sonnet-4-6", "https://api.xiaomimimo.com/v1"),
    ]
    print("\n选择模型服务商：")
    default_index = 1
    for idx, (provider, label, _, api_base) in enumerate(choices, 1):
        if provider == default and not api_base:
            default_index = idx
            break
    for idx, (_, label, _, _) in enumerate(choices, 1):
        marker = " (默认)" if idx == default_index else ""
        print(f"  {idx}. {label}{marker}")

    raw = _prompt_default("输入序号", str(default_index))
    try:
        index = int(raw)
    except ValueError:
        index = default_index
    if index < 1 or index > len(choices):
        index = default_index
    provider, _, model, api_base = choices[index - 1]
    return provider, model, api_base


def _env_api_key(provider: str, api_base: str) -> tuple[str, str]:
    import os

    if os.environ.get("CHATCLI_API_KEY"):
        return "CHATCLI_API_KEY", os.environ["CHATCLI_API_KEY"]
    if "xiaomimimo.com" in api_base.lower():
        value = os.environ.get("MIMO_API_KEY") or os.environ.get("OPENAI_API_KEY", "")
        return ("MIMO_API_KEY" if os.environ.get("MIMO_API_KEY") else "OPENAI_API_KEY"), value
    if provider == "anthropic":
        return "ANTHROPIC_API_KEY", os.environ.get("ANTHROPIC_API_KEY", "")
    return "OPENAI_API_KEY", os.environ.get("OPENAI_API_KEY", "")


def _read_config_data(config_file: Path) -> dict:
    if not config_file.exists():
        return {}
    data = yaml.safe_load(config_file.read_text(encoding="utf-8")) or {}
    return data if isinstance(data, dict) else {}


# ── Tool path fields supported by the config ────────────────────────
# (field, env_var, description, example)
_TOOL_PATH_FIELDS = (
    ("ida_path", "IDA_PATH", "IDA Pro 路径", '例如 D:/IDA Pro/idat.exe'),
    ("ghidra_path", "GHIDRA_HEADLESS_PATH", "Ghidra 路径", '例如 D:/Tools/ghidra_11.1.2_PUBLIC'),
    ("die_path", "DIE_PATH", "Detect It Easy 路径", '例如 D:/Tools/DetectItEasy/stuff/diec.exe'),
    ("exiftool_path", "EXIFTOOL_PATH", "ExifTool 路径", '例如 D:/Tools/exiftool.exe'),
    ("upx_path", "UPX_PATH", "UPX 路径", '例如 D:/Tools/upx.exe'),
    ("sysmon_path", "SYSMON_PATH", "Sysmon 路径", '例如 C:/Program Files/reverseTools/Sysmon.exe'),
    ("x64dbg_path", "X64DBG_PATH", "x64dbg 路径", '例如 C:/Program Files/reverseTools/x64dbg.exe'),
    ("capa_path", "CAPA_PATH", "capa 路径 (flare-capa)", '例如 D:/Tools/capa.exe'),
    ("floss_path", "FLOSS_PATH", "FLOSS 路径 (flare-floss)", '例如 D:/Tools/floss.exe'),
    ("yara_path", "YARA_PATH", "YARA 路径 (yara64.exe)", '例如 D:/Tools/yara64.exe'),
)


def _detected_tool_path(field: str, env_var: str) -> str:
    """Return a tool path from environment variables, preferring the
    GHIDRA_HOME fallback for ghidra_path."""
    value = os.environ.get(env_var, "")
    if value:
        return value
    if field == "ghidra_path":
        return os.environ.get("GHIDRA_HOME", "")
    return ""


def _write_tool_paths(config_file: Path, paths: dict[str, str]) -> None:
    """Persist tool paths into an existing config file."""
    data = _read_config_data(config_file)
    for field, value in paths.items():
        if value:
            data[field] = value
        else:
            data.pop(field, None)
    config_file.write_text(
        yaml.safe_dump(data, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def _guide_tool_paths(config_file: Path) -> None:
    """Interactive wizard for tool paths."""
    print("\n" + "=" * 50)
    print("  工具路径配置（全部可跳过，之后手动编辑配置文件或设环境变量即可）")
    print("=" * 50)

    data = _read_config_data(config_file)
    paths: dict[str, str] = {}

    for field, env_var, description, example in _TOOL_PATH_FIELDS:
        current = data.get(field, "") or _detected_tool_path(field, env_var)
        hint = f" [检测到: {current}]" if current else ""
        print(f"\n{description}")
        if env_var:
            print(f"  环境变量: {env_var}{hint}")
        print(f"  {example}")
        value = _prompt_default("  路径（留空跳过）", "").strip()
        if value:
            paths[field] = value
        elif current:
            # Preserve the env-var-detected value in the config so it
            # survives across sessions even if the env var is unset later.
            paths[field] = current

    if paths:
        _write_tool_paths(config_file, paths)
        print(f"\n工具路径已写入: {config_file}")
    else:
        print("\n跳过工具路径配置。")

    return paths


# ── IDA MCP defaults derived from ida_path ─────────────────────────

_IDA_MCP_DEFAULT_URL = "http://127.0.0.1:13337/mcp"


def _derive_ida_mcp_defaults(ida_path: str) -> dict[str, object]:
    """Return sensible IDA MCP defaults when ida_path is configured.

    Supports both GUI IDA MCP plugin (port 13337) and headless idalib-mcp.
    The runtime probes the URL first; if unavailable and auto_start is enabled
    it tries the start_command as a fallback — whichever works gets used.
    """
    return {
        "ida_mcp_url": _IDA_MCP_DEFAULT_URL,
        "ida_mcp_start_command": "py -m idalib_mcp.server --port 13337",
        "ida_mcp_auto_prepare": True,
        "ida_mcp_auto_start": True,
        "ida_mcp_tool_limit": 80,
    }


def _guide_ida_mcp(config_file: Path, ida_path: str) -> None:
    """Auto-configure IDA MCP settings derived from ida_path."""
    print("\n" + "=" * 50)
    print("  IDA MCP 连接配置（根据 ida_path 自动生成默认值）")
    print("=" * 50)

    data = _read_config_data(config_file)
    defaults = _derive_ida_mcp_defaults(ida_path)

    # ── MCP URL ──
    current_url = data.get("ida_mcp_url") or os.environ.get("IDA_MCP_URL") or defaults["ida_mcp_url"]
    env_hint = " [环境变量 IDA_MCP_URL]" if os.environ.get("IDA_MCP_URL") else ""
    print(f"\nIDA MCP 服务地址{env_hint}")
    url = _prompt_default(f"  URL", current_url).strip()
    if not url:
        url = current_url

    # ── Start command ──
    default_cmd = defaults.get("ida_mcp_start_command", "")
    current_cmd = data.get("ida_mcp_start_command") or os.environ.get("IDA_MCP_START_COMMAND") or default_cmd
    env_hint = " [环境变量 IDA_MCP_START_COMMAND]" if os.environ.get("IDA_MCP_START_COMMAND") else ""
    print(f"\nIDA MCP 启动命令（headless 模式，GUI IDA 可留空）{env_hint}")
    cmd = _prompt_default(f"  start_command", current_cmd).strip()

    # ── Auto prepare ──
    current_prepare = data.get("ida_mcp_auto_prepare")
    if current_prepare is None:
        current_prepare = defaults["ida_mcp_auto_prepare"]
    print(f"\n启动时自动探测 IDA MCP 工具列表？")
    auto_prepare = _prompt_default(f"  auto_prepare (true/false)", str(current_prepare).lower()).strip()
    if auto_prepare:
        auto_prepare_val = auto_prepare in {"true", "1", "yes", "y"}
    else:
        auto_prepare_val = bool(current_prepare)

    # ── Auto start ──
    current_start = data.get("ida_mcp_auto_start")
    if current_start is None:
        current_start = defaults["ida_mcp_auto_start"]
    print(f"\nMCP 不可用时自动尝试启动？（需要 start_command）")
    auto_start = _prompt_default(f"  auto_start (true/false)", str(current_start).lower()).strip()
    if auto_start:
        auto_start_val = auto_start in {"true", "1", "yes", "y"}
    else:
        auto_start_val = bool(current_start)

    # ── Tool limit ──
    current_limit = data.get("ida_mcp_tool_limit") or defaults["ida_mcp_tool_limit"]
    print(f"\nMCP 工具数量上限")
    limit_str = _prompt_default(f"  tool_limit", str(current_limit)).strip()
    try:
        tool_limit = int(limit_str)
    except ValueError:
        tool_limit = int(current_limit)

    # ── Write ──
    mcp_settings = {
        "ida_mcp_url": url,
        "ida_mcp_auto_prepare": auto_prepare_val,
        "ida_mcp_auto_start": auto_start_val,
        "ida_mcp_tool_limit": tool_limit,
    }
    if cmd:
        mcp_settings["ida_mcp_start_command"] = cmd

    data = _read_config_data(config_file)
    data.update(mcp_settings)
    config_file.write_text(
        yaml.safe_dump(data, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )
    print(f"\nIDA MCP 配置已写入: {config_file}")


def _write_provider_settings(config_file: Path, settings: dict[str, str], preserve_template: bool) -> None:
    config_file.parent.mkdir(parents=True, exist_ok=True)
    if preserve_template:
        config_file.write_text(_render_config(settings), encoding="utf-8")
        return

    data = _read_config_data(config_file)
    provider_data = data.setdefault("provider", {})
    provider_data["provider"] = settings["provider"]
    provider_data["model"] = settings["model"]
    if settings.get("api_base"):
        provider_data["api_base"] = settings["api_base"]
    else:
        provider_data.pop("api_base", None)
    if settings.get("api_key"):
        provider_data["api_key"] = settings["api_key"]
    config_file.write_text(
        yaml.safe_dump(data, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def guide_config(config_file: Path, preserve_template: bool = False) -> None:
    data = _read_config_data(config_file)
    provider_data = data.get("provider", {}) if isinstance(data.get("provider"), dict) else {}
    detected = _detected_provider_settings()

    current_provider = provider_data.get("provider") or detected["provider"]
    provider, default_model, default_api_base = _choose_provider(current_provider)

    current_model = provider_data.get("model") or detected.get("model") or default_model
    if current_provider != provider:
        current_model = default_model
    model = _prompt_default("模型名", current_model)

    current_api_base = provider_data.get("api_base") or detected.get("api_base") or default_api_base
    if provider in {"openai-compatible", "text-tools"}:
        api_base = _prompt_default("API base URL", current_api_base)
    else:
        api_base = _prompt_default("API base URL（默认通常留空）", current_api_base)

    env_name, env_key = _env_api_key(provider, api_base)
    api_key = ""
    if env_key:
        print(f"检测到 {env_name}，不会把 key 写入配置文件。")
    else:
        print("未检测到 API key。可以留空，之后用环境变量配置；也可以写入本地配置文件。")
        api_key = getpass.getpass("API key（留空跳过）: ").strip()

    _write_provider_settings(
        config_file,
        {
            "provider": provider,
            "model": model,
            "api_base": api_base,
            "api_key": api_key,
        },
        preserve_template=preserve_template,
    )
    print(f"配置已更新：{config_file}")

    tool_paths = _guide_tool_paths(config_file)
    if tool_paths.get("ida_path"):
        _guide_ida_mcp(config_file, tool_paths["ida_path"])


def _first_run_config_file(config_file: Path | None = None) -> Path | None:
    if config_file is not None:
        return None if config_file.exists() else config_file
    if os.environ.get("CHATCLI_CONFIG"):
        config_file = Config.default_config_file()
        return None if config_file.exists() else config_file
    if Config.find_config_file() is None:
        return Config.default_config_file()
    return None


def ensure_first_run_config(interactive: bool, config_file: Path | None = None) -> Config:
    requested_config_file = config_file
    first_run_config_file = _first_run_config_file(requested_config_file)
    if first_run_config_file is not None:
        settings = _detected_provider_settings()
        setup_config(first_run_config_file, settings=settings, quiet=not interactive)
        if interactive:
            print("未发现当前环境配置文件，已自动创建默认配置。")
            guide_config(first_run_config_file, preserve_template=True)

    config = Config.load(str(requested_config_file) if requested_config_file else None)
    if not config.provider.api_key and interactive:
        config_file = requested_config_file or Config.find_config_file() or Config.default_config_file()
        print("\n当前配置还没有可用 API key，进入配置向导。")
        guide_config(config_file, preserve_template=False)
        config = Config.load(str(config_file) if config_file else None)
    return config


def main():
    force_resume = False
    force_evolve = False
    force_print = False
    evolve_focus = ""
    setup_requested = False
    setup_scope = "local"
    config_override: Path | None = None
    positional: list[str] = []
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        arg = args[i]
        if arg in ("--setup", "-s"):
            setup_requested = True
        elif arg == "--global":
            setup_scope = "global"
            config_override = Config.global_config_file()
        elif arg in ("--local", "--project"):
            setup_scope = "local"
            config_override = Config.local_config_file()
        if arg in ("--version", "-v"):
            from . import __version__
            print(f"chatcli v{__version__}")
            return
        if arg in ("--help", "-h"):
            print(__doc__)
            return
        if arg in ("--resume", "-r"):
            force_resume = True
        elif arg in ("--evolve", "-e"):
            force_evolve = True
        elif arg in ("--print", "-p"):
            force_print = True
        elif arg == "--focus" and i + 1 < len(args):
            evolve_focus = args[i + 1]
            i += 1
        elif arg in ("--setup", "-s", "--global", "--local", "--project"):
            pass
        else:
            positional.append(arg)
        i += 1

    if setup_requested:
        config_file = (
            Config.global_config_file()
            if setup_scope == "global"
            else Config.default_config_file()
        )
        preserve_template = not config_file.exists()
        config_file = setup_config(config_file)
        if sys.stdin.isatty() and sys.stdout.isatty():
            guide_config(config_file, preserve_template=preserve_template)
        return

    # Load config, creating first-run config when none exists.
    interactive_setup = sys.stdin.isatty() and sys.stdout.isatty()
    config = ensure_first_run_config(interactive_setup, config_override)

    # Check for API key
    if not config.provider.api_key:
        print(
            "Error: No API key found. Set CHATCLI_API_KEY, ANTHROPIC_API_KEY, "
            "OPENAI_API_KEY, or MIMO_API_KEY."
        )
        print("Or run 'chatcli --setup' to configure provider settings interactively.")
        sys.exit(1)

    # Single-shot mode (skip if a mode flag was set)
    query = " ".join(positional).strip()
    if not query and force_print and not sys.stdin.isatty():
        query = sys.stdin.read().strip()

    if query and not force_resume and not force_evolve:
        from .checkpoint import mark_clean
        repl = REPL(config)
        try:
            if query.lstrip().startswith("/"):
                handled = repl._handle_command(query)
                if handled is not None:
                    return
            repl.agent.run(query)
            repl._process_auto_requests()
        finally:
            mark_clean(config.workspace)
        return

    if force_print and not query:
        print("Error: --print requires a query argument or piped stdin.")
        sys.exit(1)

    # Interactive REPL
    repl = REPL(config)
    if force_resume or config.auto_resume:
        repl._resume_flag = True
    if force_evolve:
        repl._evolve_flag = True
        repl._evolve_focus = evolve_focus
    repl.run()


if __name__ == "__main__":
    main()
