"""ATT&CK-style mapping tables for malware behavior categories."""

TECHNIQUE_MAP = {
    "initial_access_artifact": [("Initial Access / Execution", "T1204", "User Execution")],
    "loader_staging": [("Defense Evasion", "T1027", "Obfuscated Files or Information")],
    "api_hashing_obfuscation": [("Defense Evasion", "T1027", "Obfuscated Files or Information")],
    "dll_sideload_hijack": [("Defense Evasion", "T1574.002", "Hijack Execution Flow: DLL Side-Loading")],
    "lotl_abuse": [("Defense Evasion / Execution", "T1218", "System Binary Proxy Execution")],
    "command_execution": [("Execution", "T1059", "Command and Scripting Interpreter")],
    "process_injection": [("Defense Evasion / Privilege Escalation", "T1055", "Process Injection")],
    "defense_evasion": [("Defense Evasion", "T1497", "Virtualization/Sandbox Evasion")],
    "security_tool_tampering": [("Defense Evasion", "T1562", "Impair Defenses")],
    "persistence": [("Persistence", "T1547", "Boot or Logon Autostart Execution")],
    "privilege_escalation": [("Privilege Escalation", "T1134", "Access Token Manipulation")],
    "rootkit_driver": [("Defense Evasion / Persistence", "T1014", "Rootkit")],
    "bootkit_uefi": [("Persistence / Defense Evasion", "T1542", "Pre-OS Boot")],
    "discovery": [("Discovery", "T1082", "System Information Discovery")],
    "ad_discovery": [("Discovery", "T1482", "Domain Trust Discovery")],
    "credential_access": [("Credential Access", "T1003", "OS Credential Dumping")],
    "browser_cloud_credentials": [("Credential Access", "T1555", "Credentials from Password Stores")],
    "keylogging_capture": [("Collection / Credential Access", "T1056.001", "Input Capture: Keylogging")],
    "wallet_clipboard_hijack": [("Collection", "T1115", "Clipboard Data")],
    "collection": [("Collection", "T1005", "Data from Local System")],
    "cloud_container": [("Credential Access / Discovery", "T1552", "Unsecured Credentials")],
    "mobile_iot": [("Discovery / Collection", "", "Platform-Specific Collection or Discovery")],
    "c2_network": [("Command and Control", "T1071", "Application Layer Protocol")],
    "c2_variants": [("Command and Control", "T1090", "Proxy")],
    "rat_backdoor_control": [("Command and Control", "T1105", "Ingress Tool Transfer")],
    "lateral_movement": [("Lateral Movement", "T1021", "Remote Services")],
    "worm_propagation": [("Lateral Movement", "T1105", "Ingress Tool Transfer")],
    "exfiltration": [("Exfiltration", "T1041", "Exfiltration Over C2 Channel")],
    "ddos_bot_proxy": [("Impact / Command and Control", "T1498", "Network Denial of Service")],
    "miner": [("Impact", "T1496", "Resource Hijacking")],
    "file_infector": [("Impact / Defense Evasion", "", "File Infection or Executable Modification")],
    "supply_chain_update_abuse": [("Initial Access / Persistence", "T1195", "Supply Chain Compromise")],
    "ransomware_anti_recovery": [("Impact", "T1486", "Data Encrypted for Impact")],
    "impact": [("Impact", "T1485", "Data Destruction")],
}

HIGH_IMPACT = {
    "c2_network",
    "c2_variants",
    "rat_backdoor_control",
    "process_injection",
    "credential_access",
    "browser_cloud_credentials",
    "keylogging_capture",
    "wallet_clipboard_hijack",
    "exfiltration",
    "lateral_movement",
    "worm_propagation",
    "impact",
    "ransomware_anti_recovery",
    "security_tool_tampering",
    "rootkit_driver",
    "bootkit_uefi",
    "miner",
    "ddos_bot_proxy",
    "file_infector",
    "supply_chain_update_abuse",
}

