"""ATT&CK-style mapping tables for malware behavior categories."""

TECHNIQUE_MAP = {
    "initial_access_artifact": [("Initial Access / Execution", "T1204", "User Execution")],
    "silent_downloader": [("Command and Control", "T1105", "Ingress Tool Transfer")],
    "payload_dropper": [("Execution / Defense Evasion", "T1027", "Obfuscated Files or Information")],
    "loader_staging": [("Defense Evasion", "T1027", "Obfuscated Files or Information")],
    "api_hashing_obfuscation": [("Defense Evasion", "T1027", "Obfuscated Files or Information")],
    "dll_sideload_hijack": [("Defense Evasion", "T1574.002", "Hijack Execution Flow: DLL Side-Loading")],
    "lotl_abuse": [("Defense Evasion / Execution", "T1218", "System Binary Proxy Execution")],
    "command_execution": [("Execution", "T1059", "Command and Scripting Interpreter")],
    "process_injection": [("Defense Evasion / Privilege Escalation", "T1055", "Process Injection")],
    "process_masquerading": [("Defense Evasion", "T1036", "Masquerading")],
    "defense_evasion": [("Defense Evasion", "T1497", "Virtualization/Sandbox Evasion")],
    "anti_debug": [("Defense Evasion", "T1622", "Debugger Evasion")],
    "anti_vm_sandbox": [("Defense Evasion", "T1497", "Virtualization/Sandbox Evasion")],
    "execution_delay": [("Defense Evasion", "T1497.003", "Time Based Evasion")],
    "telemetry_bypass": [("Defense Evasion", "T1562", "Impair Defenses")],
    "security_tool_tampering": [("Defense Evasion", "T1562", "Impair Defenses")],
    "persistence": [("Persistence", "T1547", "Boot or Logon Autostart Execution")],
    "scheduled_task_persistence": [("Execution / Persistence", "T1053.005", "Scheduled Task/Job: Scheduled Task")],
    "startup_folder_persistence": [("Persistence", "T1547.001", "Boot or Logon Autostart Execution: Registry Run Keys / Startup Folder")],
    "service_persistence": [("Persistence / Privilege Escalation", "T1543.003", "Create or Modify System Process: Windows Service")],
    "wmi_persistence": [("Persistence", "T1546.003", "Event Triggered Execution: Windows Management Instrumentation Event Subscription")],
    "registry_autostart_extension_persistence": [("Persistence", "T1547", "Boot or Logon Autostart Execution")],
    "ifeo_debugger_persistence": [("Persistence / Privilege Escalation", "T1546.012", "Event Triggered Execution: Image File Execution Options Injection")],
    "accessibility_hijack_persistence": [("Persistence / Privilege Escalation", "T1546.008", "Event Triggered Execution: Accessibility Features")],
    "bits_jobs_persistence": [("Persistence", "T1197", "BITS Jobs")],
    "account_persistence": [("Persistence", "T1136", "Create Account")],
    "privilege_escalation": [("Privilege Escalation", "T1134", "Access Token Manipulation")],
    "uac_bypass": [("Privilege Escalation / Defense Evasion", "T1548.002", "Abuse Elevation Control Mechanism: Bypass User Account Control")],
    "byovd_abuse": [("Privilege Escalation / Defense Evasion", "T1068", "Exploitation for Privilege Escalation")],
    "rootkit_driver": [("Defense Evasion / Persistence", "T1014", "Rootkit")],
    "bootkit_uefi": [("Persistence / Defense Evasion", "T1542", "Pre-OS Boot")],
    "discovery": [("Discovery", "T1082", "System Information Discovery")],
    "ad_discovery": [("Discovery", "T1482", "Domain Trust Discovery")],
    "credential_access": [("Credential Access", "T1003", "OS Credential Dumping")],
    "banking_credential_theft": [("Credential Access / Collection", "T1056.003", "Input Capture: Web Portal Capture")],
    "lsass_dumping": [("Credential Access", "T1003.001", "OS Credential Dumping: LSASS Memory")],
    "silent_process_exit_dump": [("Credential Access", "T1003.001", "OS Credential Dumping: LSASS Memory")],
    "ssp_credential_capture": [("Credential Access / Defense Evasion", "T1556.002", "Modify Authentication Process: Security Support Provider")],
    "registry_credential_dumping": [("Credential Access", "T1003.002/T1003.004/T1003.005", "OS Credential Dumping: SAM, LSA Secrets, and Cached Domain Credentials")],
    "ntds_dumping": [("Credential Access", "T1003.003", "OS Credential Dumping: NTDS")],
    "dcsync_replication": [("Credential Access", "T1003.006", "OS Credential Dumping: DCSync")],
    "kerberos_ticket_access": [("Credential Access", "T1558", "Steal or Forge Kerberos Tickets")],
    "dpapi_credential_access": [("Credential Access", "T1555", "Credentials from Password Stores")],
    "ssh_private_key_access": [("Credential Access", "T1552.004", "Unsecured Credentials: Private Keys")],
    "unix_shadow_access": [("Credential Access", "T1003.008", "OS Credential Dumping: /etc/passwd and /etc/shadow")],
    "browser_cloud_credentials": [("Credential Access", "T1555", "Credentials from Password Stores")],
    "keylogging_capture": [("Collection / Credential Access", "T1056.001", "Input Capture: Keylogging")],
    "wallet_clipboard_hijack": [("Collection", "T1115", "Clipboard Data")],
    "adware_browser_manipulation": [("Defense Evasion / Collection", "T1112", "Modify Registry")],
    "browser_extension_toolbar": [("Persistence", "T1176", "Browser Extensions")],
    "user_deception_fraud": [("Initial Access / Collection", "T1204", "User Execution")],
    "collection": [("Collection", "T1005", "Data from Local System")],
    "archive_staging": [("Collection", "T1560", "Archive Collected Data")],
    "cloud_container": [("Credential Access / Discovery", "T1552", "Unsecured Credentials")],
    "mobile_iot": [("Discovery / Collection", "", "Platform-Specific Collection or Discovery")],
    "c2_network": [("Command and Control", "T1071", "Application Layer Protocol")],
    "c2_config_protocol": [("Command and Control", "T1071", "Application Layer Protocol")],
    "named_pipe_ipc": [("Execution / Command and Control", "T1559", "Inter-Process Communication")],
    "c2_variants": [("Command and Control", "T1090", "Proxy")],
    "remote_access_tool_abuse": [("Command and Control", "T1219", "Remote Access Software")],
    "rat_backdoor_control": [("Command and Control", "T1105", "Ingress Tool Transfer")],
    "lateral_movement": [("Lateral Movement", "T1021", "Remote Services")],
    "worm_propagation": [("Lateral Movement", "T1105", "Ingress Tool Transfer")],
    "exfiltration": [("Exfiltration", "T1041", "Exfiltration Over C2 Channel")],
    "ddos_bot_proxy": [("Impact / Command and Control", "T1498", "Network Denial of Service")],
    "miner": [("Impact", "T1496", "Resource Hijacking")],
    "file_infector": [("Impact / Defense Evasion", "", "File Infection or Executable Modification")],
    "supply_chain_update_abuse": [("Initial Access / Persistence", "T1195", "Supply Chain Compromise")],
    "ransomware_anti_recovery": [("Impact", "T1486", "Data Encrypted for Impact")],
    "impact": [("Impact", "T1485", "Data Destruction")],
}

HIGH_IMPACT = {
    "c2_network",
    "c2_variants",
    "silent_downloader",
    "payload_dropper",
    "rat_backdoor_control",
    "process_injection",
    "process_masquerading",
    "anti_debug",
    "anti_vm_sandbox",
    "execution_delay",
    "telemetry_bypass",
    "uac_bypass",
    "byovd_abuse",
    "wmi_persistence",
    "scheduled_task_persistence",
    "startup_folder_persistence",
    "service_persistence",
    "registry_autostart_extension_persistence",
    "ifeo_debugger_persistence",
    "accessibility_hijack_persistence",
    "bits_jobs_persistence",
    "account_persistence",
    "credential_access",
    "banking_credential_theft",
    "lsass_dumping",
    "silent_process_exit_dump",
    "ssp_credential_capture",
    "registry_credential_dumping",
    "ntds_dumping",
    "dcsync_replication",
    "kerberos_ticket_access",
    "dpapi_credential_access",
    "ssh_private_key_access",
    "unix_shadow_access",
    "browser_cloud_credentials",
    "keylogging_capture",
    "wallet_clipboard_hijack",
    "browser_extension_toolbar",
    "user_deception_fraud",
    "exfiltration",
    "archive_staging",
    "lateral_movement",
    "worm_propagation",
    "impact",
    "ransomware_anti_recovery",
    "security_tool_tampering",
    "c2_config_protocol",
    "named_pipe_ipc",
    "remote_access_tool_abuse",
    "rootkit_driver",
    "bootkit_uefi",
    "miner",
    "ddos_bot_proxy",
    "file_infector",
    "supply_chain_update_abuse",
}

